version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: kora_world_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kora_network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: kora_world_api
    restart: unless-stopped
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
      DHL_API_KEY: ${DHL_API_KEY}
    ports:
      - '3010:3000'
    depends_on:
      - postgres
    networks:
      - kora_network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    container_name: kora_world_web
    restart: unless-stopped
    ports:
      - '4210:80'
    networks:
      - kora_network

volumes:
  postgres_data:

networks:
  kora_network:
    driver: bridge
